# Generated by Django 2.2.5 on 2019-11-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0005_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='usr/'),
        ),
    ]
